name: Java CI/CD with Gradle

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write application properties
        uses: DamianReeves/write-file-action@v1.3
        with:
          path: ./src/main/resources/application.properties
          contents: |
            ${{ secrets.SPRING_PROPERTIES }}
          write-mode: overwrite

      - name: Setup JDK 24
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Ensure Gradle is executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.4.0
        with:
          cache-disabled: true
          gradle-version: 'wrapper'
      - run: gradle build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}

      - name: Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}